"""Prompt templates for memory subsystems (review + summary)."""

REVIEW_PROMPT = (
    "Read the personal-finance conversation above between the user and AI.\n\n"
    "Find memorable facts about the user:\n"
    "1. Financial habits (e.g., 'forgets to log cash', 'salary paid on the 15th')\n"
    "2. Preferences (e.g., 'prefers weekly reports')\n"
    "3. Goals (e.g., 'saving 50M for a car', 'paying off debt')\n"
    "4. Personal context (e.g., 'spouse manages separate finances', 'student')\n\n"
    "RULES:\n"
    "- Return a JSON array. Each item has:\n"
    "  - 'action': 'add' (new fact) or 'replace' (update an existing fact)\n"
    "  - 'fact', 'category', 'importance', 'confidence', 'expires_in_days' (optional)\n"
    "  - If action='replace', include 'replaces': 1-based index from 'Known facts' list\n"
    "- Use 'replace' when the new fact refines/supersedes an existing one\n"
    "  (e.g., savings goal raised from 50M to 80M → replace old goal, merge info).\n"
    "- Use 'add' for a new topic not covered by any existing fact.\n"
    "- If info already exists in known facts and has NOT changed, omit it.\n"
    "- Each fact must be one short sentence.\n"
    "- Write the fact text in the SAME LANGUAGE as the conversation above.\n"
    "- If nothing new is found, return []\n\n"
    "category: preference | habit | goal | context | general\n"
    "importance: 1-10 (9-10 core; 6-8 frequently useful; 3-5 supplementary; 1-2 incidental)\n"
    "confidence: 1-10 — how certain are you the user actually said/meant this? "
    "9-10 explicit statement; 6-8 strongly implied; 3-5 inferred; 1-2 a guess.\n"
    "expires_in_days: null = evergreen. E.g. 'currently a student' → 365, "
    "'dieting this month' → 30\n\n"
    "Return ONLY JSON, no explanation.\n"
    "Example:\n"
    "[\n"
    "  {\"action\": \"add\", \"fact\": \"Has 2 young children\","
    " \"category\": \"context\",\n"
    "   \"importance\": 7, \"confidence\": 9},\n"
    "  {\"action\": \"replace\", \"replaces\": 3,"
    " \"fact\": \"Savings goal: 80M (raised from 50M)\",\n"
    "   \"category\": \"goal\", \"importance\": 9, \"confidence\": 10}\n"
    "]"
)


CONSOLIDATION_PROMPT = (
    "You are consolidating a user's long-term fact store. The numbered list "
    "above is everything currently remembered about them.\n\n"
    "Find pairs or clusters that say the same thing in different words "
    "(paraphrases, refinements, contradictions where the newer fact wins). "
    "For each cluster, emit ONE 'merge' action that keeps the strongest "
    "phrasing and removes the redundant rows.\n\n"
    "RULES:\n"
    "- Return a JSON array of 'merge' actions ONLY. Never emit 'add' or "
    "anything else — consolidation never invents new facts.\n"
    "- Each item: 'action': 'merge', 'keeps': 1-based survivor index, "
    "'removes': list of 1-based indices to delete, 'fact': merged text "
    "(survivor will be overwritten with this), 'category', 'importance', "
    "'confidence'.\n"
    "- 'keeps' must NOT appear in 'removes'.\n"
    "- Skip clusters where the facts are genuinely independent.\n"
    "- If nothing is mergeable, return [].\n\n"
    "category: preference | habit | goal | context | general\n"
    "importance, confidence: 1-10.\n\n"
    "Return ONLY JSON, no explanation.\n"
    "Example:\n"
    "[\n"
    "  {\"action\": \"merge\", \"keeps\": 3, \"removes\": [7, 12],\n"
    "   \"fact\": \"Mục tiêu tiết kiệm 80M để mua xe (ưu tiên cao)\",\n"
    "   \"category\": \"goal\", \"importance\": 9, \"confidence\": 9}\n"
    "]"
)


SUMMARY_PROMPT = (
    "Summarize the personal-finance conversation above.\n\n"
    "Requirements:\n"
    "- summary: 2-4 sentences. State what the user asked, what was done, what "
    "was concluded. No greetings, no meta-comments, no honorifics. Write in "
    "the SAME LANGUAGE as the conversation above.\n"
    "- key_topics: 2-5 main topics, each 1-3 words (e.g., \"budget\", "
    "\"car savings\", \"food spending\" / \"ngân sách\", \"tiết kiệm mua xe\"). "
    "Match the conversation's language.\n"
    "- outcome: ONE short sentence describing what got decided or accomplished "
    "(e.g., \"Set April food budget to 5M\" / \"Đã lập budget ăn uống tháng 4 "
    "5tr\"). Use null if the session reached no concrete outcome.\n"
    "- If the session is only greetings / no substance, use "
    "summary='No substantive content.', key_topics=[], outcome=null.\n\n"
    "Return ONLY a JSON object (no markdown, no explanation):\n"
    '{"summary": "...", "key_topics": ["...", "..."], "outcome": "..."}'
)
